[workspace]
members = [
    "node",
    "pallets/template",
    "runtime",
    "consensus/sha3pow",
    "consensus/minipow",
]
exclude = ["contract/health-record"]
[profile.release]
panic = "unwind"
